export const COUNTRIES = Object.freeze([
  { code: 'FR', name: 'France', difficulty: 200 },
  { code: 'BE', name: 'Belgique', difficulty: 155 },
  { code: 'CH', name: 'Suisse', difficulty: 150 },
  { code: 'DE', name: 'Allemagne', difficulty: 195 },
  { code: 'AT', name: 'Autriche', difficulty: 150 },
  { code: 'LU', name: 'Luxembourg', difficulty: 130 },
  { code: 'NL', name: 'Pays-Bas', difficulty: 180 },
  { code: 'IE', name: 'Irlande', difficulty: 165 },
  { code: 'GB', name: 'Royaume-Uni', difficulty: 200 },
  { code: 'PT', name: 'Portugal', difficulty: 180 },
  { code: 'ES', name: 'Espagne', difficulty: 195 },
  { code: 'IT', name: 'Italie', difficulty: 200 },
  { code: 'DK', name: 'Danemark', difficulty: 140 },
  { code: 'SE', name: 'Suède', difficulty: 165 },
  { code: 'NO', name: 'Norvège', difficulty: 160 },
  { code: 'FI', name: 'Finlande', difficulty: 150 },
  { code: 'IS', name: 'Islande', difficulty: 130 },
  { code: 'PL', name: 'Pologne', difficulty: 170 },
  { code: 'CZ', name: 'Tchéquie', difficulty: 140 },
  { code: 'SK', name: 'Slovaquie', difficulty: 120 },
  { code: 'HU', name: 'Hongrie', difficulty: 140 },
  { code: 'RO', name: 'Roumanie', difficulty: 140 },
  { code: 'BG', name: 'Bulgarie', difficulty: 110 },
  { code: 'HR', name: 'Croatie', difficulty: 140 },
  { code: 'SI', name: 'Slovénie', difficulty: 110 },
  { code: 'GR', name: 'Grèce', difficulty: 180 },
  { code: 'EE', name: 'Estonie', difficulty: 90 },
  { code: 'LV', name: 'Lettonie', difficulty: 90 },
  { code: 'LT', name: 'Lituanie', difficulty: 90 },
  { code: 'UA', name: 'Ukraine', difficulty: 170 },
  { code: 'RU', name: 'Russie', difficulty: 200 },
  { code: 'TR', name: 'Turquie', difficulty: 180 },
  { code: 'AD', name: 'Andorre', difficulty: 120 },
  { code: 'MC', name: 'Monaco', difficulty: 160 },
  { code: 'LI', name: 'Liechtenstein', difficulty: 90 },
  { code: 'SM', name: 'Saint-Marin', difficulty: 90 },
  { code: 'VA', name: 'Vatican', difficulty: 130 },
  { code: 'RS', name: 'Serbie', difficulty: 120 },
  { code: 'ME', name: 'Monténégro', difficulty: 100 },
  { code: 'MK', name: 'Macédoine du Nord', difficulty: 95 },
  { code: 'AL', name: 'Albanie', difficulty: 120 },
  { code: 'BA', name: 'Bosnie-Herzégovine', difficulty: 100 },
  { code: 'MD', name: 'Moldavie', difficulty: 90 },
  { code: 'MA', name: 'Maroc', difficulty: 175 },
  { code: 'DZ', name: 'Algérie', difficulty: 160 },
  { code: 'TN', name: 'Tunisie', difficulty: 155 },
  { code: 'EG', name: 'Égypte', difficulty: 185 },
  { code: 'SA', name: 'Arabie saoudite', difficulty: 170 },
  { code: 'AE', name: 'Émirats arabes unis', difficulty: 165 },
  { code: 'QA', name: 'Qatar', difficulty: 150 },
  { code: 'IR', name: 'Iran', difficulty: 150 },
  { code: 'IQ', name: 'Irak', difficulty: 140 },
  { code: 'JO', name: 'Jordanie', difficulty: 140 },
  { code: 'LB', name: 'Liban', difficulty: 150 },
  { code: 'SY', name: 'Syrie', difficulty: 150 },
  { code: 'OM', name: 'Oman', difficulty: 130 },
  { code: 'KW', name: 'Koweït', difficulty: 130 },
  { code: 'BH', name: 'Bahreïn', difficulty: 110 },
  { code: 'YE', name: 'Yémen', difficulty: 100 },
  { code: 'GE', name: 'Géorgie', difficulty: 120 },
  { code: 'AM', name: 'Arménie', difficulty: 120 },
  { code: 'AZ', name: 'Azerbaïdjan', difficulty: 120 },
  { code: 'KZ', name: 'Kazakhstan', difficulty: 110 },
  { code: 'UZ', name: 'Ouzbékistan', difficulty: 80 },
  { code: 'TM', name: 'Turkménistan', difficulty: 50 },
  { code: 'TJ', name: 'Tadjikistan', difficulty: 50 },
  { code: 'KG', name: 'Kirghizistan', difficulty: 60 },
  { code: 'ZA', name: 'Afrique du Sud', difficulty: 180 },
  { code: 'NG', name: 'Nigéria', difficulty: 150 },
  { code: 'GH', name: 'Ghana', difficulty: 110 },
  { code: 'CI', name: "Côte d'Ivoire", difficulty: 130 },
  { code: 'SN', name: 'Sénégal', difficulty: 130 },
  { code: 'CM', name: 'Cameroun', difficulty: 100 },
  { code: 'ML', name: 'Mali', difficulty: 80 },
  { code: 'BF', name: 'Burkina Faso', difficulty: 70 },
  { code: 'NE', name: 'Niger', difficulty: 60 },
  { code: 'TG', name: 'Togo', difficulty: 60 },
  { code: 'BJ', name: 'Bénin', difficulty: 60 },
  { code: 'GN', name: 'Guinée', difficulty: 70 },
  { code: 'GW', name: 'Guinée-Bissau', difficulty: 40 },
  { code: 'GQ', name: 'Guinée équatoriale', difficulty: 30 },
  { code: 'KE', name: 'Kenya', difficulty: 120 },
  { code: 'ET', name: 'Éthiopie', difficulty: 100 },
  { code: 'UG', name: 'Ouganda', difficulty: 80 },
  { code: 'TZ', name: 'Tanzanie', difficulty: 80 },
  { code: 'RW', name: 'Rwanda', difficulty: 60 },
  { code: 'BI', name: 'Burundi', difficulty: 40 },
  { code: 'CD', name: 'RD Congo', difficulty: 120 },
  { code: 'CG', name: 'Congo', difficulty: 70 },
  { code: 'AO', name: 'Angola', difficulty: 80 },
  { code: 'MZ', name: 'Mozambique', difficulty: 60 },
  { code: 'ZM', name: 'Zambie', difficulty: 50 },
  { code: 'ZW', name: 'Zimbabwe', difficulty: 60 },
  { code: 'NA', name: 'Namibie', difficulty: 60 },
  { code: 'BW', name: 'Botswana', difficulty: 60 },
  { code: 'LS', name: 'Lesotho', difficulty: 30 },
  { code: 'SZ', name: 'Eswatini', difficulty: 30 },
  { code: 'KM', name: 'Comores', difficulty: 20 },
  { code: 'SC', name: 'Seychelles', difficulty: 40 },
  { code: 'CV', name: 'Cap-Vert', difficulty: 70 },
  { code: 'ST', name: 'Sao Tomé-et-Principe', difficulty: 20 },
  { code: 'MG', name: 'Madagascar', difficulty: 90 },
  { code: 'SO', name: 'Somalie', difficulty: 70 },
  { code: 'SD', name: 'Soudan', difficulty: 90 },
  { code: 'SS', name: 'Soudan du Sud', difficulty: 20 },
  { code: 'LY', name: 'Libye', difficulty: 110 },
  { code: 'MR', name: 'Mauritanie', difficulty: 60 },
  { code: 'CA', name: 'Canada', difficulty: 200 },
  { code: 'US', name: 'États-Unis', difficulty: 200 },
  { code: 'MX', name: 'Mexique', difficulty: 190 },
  { code: 'CR', name: 'Costa Rica', difficulty: 110 },
  { code: 'CU', name: 'Cuba', difficulty: 150 },
  { code: 'PA', name: 'Panama', difficulty: 120 },
  { code: 'DO', name: 'République dominicaine', difficulty: 150 },
  { code: 'HT', name: 'Haïti', difficulty: 130 },
  { code: 'SV', name: 'Salvador', difficulty: 90 },
  { code: 'GT', name: 'Guatemala', difficulty: 100 },
  { code: 'HN', name: 'Honduras', difficulty: 90 },
  { code: 'NI', name: 'Nicaragua', difficulty: 90 },
  { code: 'BZ', name: 'Belize', difficulty: 60 },
  { code: 'JM', name: 'Jamaïque', difficulty: 150 },
  { code: 'TT', name: 'Trinité-et-Tobago', difficulty: 80 },
  { code: 'BB', name: 'Barbade', difficulty: 60 },
  { code: 'BS', name: 'Bahamas', difficulty: 140 },
  { code: 'BR', name: 'Brésil', difficulty: 200 },
  { code: 'AR', name: 'Argentine', difficulty: 180 },
  { code: 'CL', name: 'Chili', difficulty: 120 },
  { code: 'CO', name: 'Colombie', difficulty: 150 },
  { code: 'PE', name: 'Pérou', difficulty: 130 },
  { code: 'VE', name: 'Venezuela', difficulty: 100 },
  { code: 'UY', name: 'Uruguay', difficulty: 150 },
  { code: 'PY', name: 'Paraguay', difficulty: 80 },
  { code: 'BO', name: 'Bolivie', difficulty: 90 },
  { code: 'GY', name: 'Guyana', difficulty: 40 },
  { code: 'SR', name: 'Suriname', difficulty: 30 },
  { code: 'CN', name: 'Chine', difficulty: 200 },
  { code: 'JP', name: 'Japon', difficulty: 200 },
  { code: 'KR', name: 'Corée du Sud', difficulty: 180 },
  { code: 'TW', name: 'Taïwan', difficulty: 120 },
  { code: 'HK', name: 'Hong Kong', difficulty: 150 },
  { code: 'MO', name: 'Macao', difficulty: 100 },
  { code: 'SG', name: 'Singapour', difficulty: 170 },
  { code: 'TH', name: 'Thaïlande', difficulty: 160 },
  { code: 'VN', name: 'Viêt Nam', difficulty: 140 },
  { code: 'PH', name: 'Philippines', difficulty: 145 },
  { code: 'ID', name: 'Indonésie', difficulty: 160 },
  { code: 'MY', name: 'Malaisie', difficulty: 130 },
  { code: 'KH', name: 'Cambodge', difficulty: 90 },
  { code: 'LA', name: 'Laos', difficulty: 70 },
  { code: 'MM', name: 'Myanmar', difficulty: 90 },
  { code: 'BN', name: 'Brunei', difficulty: 60 },
  { code: 'TL', name: 'Timor oriental', difficulty: 40 },
  { code: 'IN', name: 'Inde', difficulty: 200 },
  { code: 'PK', name: 'Pakistan', difficulty: 150 },
  { code: 'BD', name: 'Bangladesh', difficulty: 140 },
  { code: 'NP', name: 'Népal', difficulty: 120 },
  { code: 'LK', name: 'Sri Lanka', difficulty: 120 },
  { code: 'AF', name: 'Afghanistan', difficulty: 150 },
  { code: 'MV', name: 'Maldives', difficulty: 80 },
  { code: 'BT', name: 'Bhoutan', difficulty: 60 },
  { code: 'AU', name: 'Australie', difficulty: 200 },
  { code: 'NZ', name: 'Nouvelle-Zélande', difficulty: 170 },
  { code: 'FJ', name: 'Fidji', difficulty: 90 },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', difficulty: 70 },
  { code: 'SB', name: 'Îles Salomon', difficulty: 40 },
  { code: 'VU', name: 'Vanuatu', difficulty: 40 },
  { code: 'WS', name: 'Samoa', difficulty: 40 },
  { code: 'TO', name: 'Tonga', difficulty: 40 },
  { code: 'TV', name: 'Tuvalu', difficulty: 20 },
  { code: 'KI', name: 'Kiribati', difficulty: 20 },
  { code: 'NR', name: 'Nauru', difficulty: 10 },
  { code: 'PW', name: 'Palaos', difficulty: 30 },
  { code: 'MH', name: 'Îles Marshall', difficulty: 20 },
  { code: 'FM', name: 'Micronésie', difficulty: 20 }
]);

export function createCountriesService() {
  return {
    list() {
      return COUNTRIES;
    }
  };
}
